# Generated by Django 5.1.1 on 2024-09-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Product',
            new_name='product',
        ),
    ]
